using VerseDeck.Core.Models;
using VerseDeck.Speech;
using VerseDeck.Voice;

namespace VerseDeck.Tests;

public class RecognitionRulesTests
{
    [Fact]
    public void GateClosed_WinsOverEverything()
    {
        Assert.Equal(RecognitionOutcome.GateClosed, RecognitionRules.Classify(CommandGrammar.Commands, 0.9, 0.4, knownPhrase: true, gateOpen: false));
    }

    [Fact]
    public void DiscardGrammar_IsDiscarded_EvenWithHighConfidence()
    {
        Assert.Equal(RecognitionOutcome.Discarded, RecognitionRules.Classify(CommandGrammar.Discard, 0.95, 0.4, knownPhrase: false, gateOpen: true));
    }

    [Fact]
    public void UnknownPhrase_IsDiscarded()
    {
        Assert.Equal(RecognitionOutcome.Discarded, RecognitionRules.Classify(CommandGrammar.Commands, 0.9, 0.4, knownPhrase: false, gateOpen: true));
    }

    [Fact]
    public void BelowTheModuleMinimum_IsLowConfidence()
    {
        Assert.Equal(RecognitionOutcome.LowConfidence, RecognitionRules.Classify(CommandGrammar.Commands, 0.39, 0.4, knownPhrase: true, gateOpen: true));
    }

    [Theory]
    [InlineData(0.40)]
    [InlineData(0.95)]
    public void KnownCommand_AtOrAboveTheMinimum_IsAccepted(double confidence)
    {
        Assert.Null(RecognitionRules.Classify(CommandGrammar.Commands, confidence, 0.4, knownPhrase: true, gateOpen: true));
    }
}

/// <summary>
/// The real Windows recogniser against speech generated by the real voice. Skipped unless VERSEDECK_VOICES_ROOT
/// points at a folder with the default voice, because the model is not part of the repository.
/// </summary>
public class RealPhraseCheckerTests
{
    private static readonly string[] DefaultPhrases =
    [
        "encender nave", "preparar nave", "activar energia", "encender motores", "apagar motores",
        "sacar tren de aterrizaje", "bajar tren", "subir tren", "activar luces", "apagar luces",
        "activar radar", "modo escaner", "activar salto", "abrir mapa", "activar escudos", "activar armas",
        "abrir puertas", "abrir carga", "comunicaciones", "eyectar", "autodestruccion", "weapons", "shields off"
    ];

    [Fact]
    public async Task Commands_AreRecognised_AndConversationIsDiscarded()
    {
        var root = Environment.GetEnvironmentVariable("VERSEDECK_VOICES_ROOT");
        var voice = VoiceCatalog.Load().Find(VoiceCatalog.DefaultVoiceId)!;
        if (string.IsNullOrEmpty(root) || !new VoiceStore(root).IsInstalled(voice) || CommandGrammar.Recognizers().Count == 0)
        {
            return;
        }

        var cacheRoot = SpeechFixture.TempFolder("checker");
        try
        {
            using var engine = new SherpaTtsEngine(new VoiceStore(root));
            var cache = new PhraseCache(cacheRoot);
            string[] spoken = ["bajar tren", "activar luces", "Vamos a por ellos.", "Necesito repostar antes de saltar."];
            var paths = new List<string>();
            foreach (var text in spoken)
            {
                paths.Add(cache.Store(voice, text, await engine.SynthesizeAsync(voice, text, CancellationToken.None)).Path);
            }

            var hits = await new WindowsPhraseChecker().CheckAsync(DefaultPhrases, paths, CancellationToken.None);

            Assert.Equal("bajar tren", hits[0].Text);
            Assert.False(hits[0].Discarded);
            Assert.Equal("activar luces", hits[1].Text);
            Assert.False(hits[1].Discarded);
            Assert.True(hits[2].Discarded || hits[2].Text is null, $"conversation taken as '{hits[2].Text}'");
            Assert.True(hits[3].Discarded || hits[3].Text is null, $"conversation taken as '{hits[3].Text}'");
        }
        finally
        {
            Directory.Delete(cacheRoot, recursive: true);
        }
    }
}
